name: Build nightly npm package

on:
  schedule:
    - cron: '0 12 */1 * *'
  workflow_dispatch:

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-npm-package.yml
    with:
      version: nightly

